version: '3.0'
  
services:
  homeassistant:
    container_name: homeassistant
    # image: ghcr.io/home-assistant/home-assistant:stable
    image: lscr.io/linuxserver/homeassistant:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    healthcheck:
          test: 'curl -m 90 -sLf http://localhost:8123 || date >> /config/healthcheck' #| pkill -9 python3'
          interval: 90s
          timeout: 60s
          retries: 2
    privileged: true
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    expose:
       - "8123"
    # ports:
    #   - '8123:8123'
    # network_mode: host
    
  mosquitto:
    container_name: mosquitto
    # image: eclipse-mosquitto:latest
    build:
      context: ./mosquitto
    user: '99'
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - TZ=America/Sao_Paulo
    healthcheck:
          test: "mosquitto_sub -E -t '#'"
          interval: 60s
          timeout: 10s
          retries: 5
    volumes:
      # - '/opt/mosquitto/config:/mosquitto/config:ro'
      - '/opt/mosquitto/log:/mosquitto/log'
      - '/opt/mosquitto/data:/mosquitto/data'
    ports:
      - '1883:1883'
      - '8883:8883'
    restart: always

networks:
  localnet:
    driver: bridge
    external: true